services:
    - type: web
      name: Linebot-TRack
      env: go
      buildCommand: go build -o app
      startCommand: ./app
      plan: free
      autoDeploy: false
      envVars:
          - key: ChannelAccessToken
            sync: false
          - key: ChannelSecret
            sync: false
